import { FixtureTypeDef } from "./types";

export const FIXTURE_TYPES: FixtureTypeDef[] = [
  {
    id: "checkout",
    labelVi: "Checkout Counter",
    defaultWidth: 2400,
    defaultDepth: 800,
    defaultHeight: 900,
    defaultShelfCount: 0,
    temperatureZone: "ambient",
    sellable: false,
    promoCapable: false,
    color: "#1c1c1c",
    borderColor: "#888888",
  },
  {
    id: "produce_shelf",
    labelVi: "Produce Shelf",
    defaultWidth: 1200,
    defaultDepth: 800,
    defaultHeight: 1200,
    defaultShelfCount: 3,
    temperatureZone: "ambient",
    sellable: true,
    promoCapable: true,
    color: "#3d2b0a",
    borderColor: "#a0522d",
  },
  {
    id: "food_cooler",
    labelVi: "Food Cooler",
    defaultWidth: 900,
    defaultDepth: 700,
    defaultHeight: 2000,
    defaultShelfCount: 4,
    temperatureZone: "chilled",
    sellable: true,
    promoCapable: false,
    color: "#0f2a1a",
    borderColor: "#4ade80",
  },
  {
    id: "pepsi_cooler",
    labelVi: "Pepsi Cooler",
    defaultWidth: 700,
    defaultDepth: 700,
    defaultHeight: 2000,
    defaultShelfCount: 5,
    temperatureZone: "chilled",
    sellable: true,
    promoCapable: false,
    color: "#001f5c",
    borderColor: "#3b82f6",
  },
  {
    id: "fresh_counter",
    labelVi: "Fresh Counter",
    defaultWidth: 1800,
    defaultDepth: 850,
    defaultHeight: 890,
    defaultShelfCount: 1,
    temperatureZone: "chilled",
    sellable: true,
    promoCapable: false,
    color: "#1a2a3a",
    borderColor: "#94a3b8",
  },
  {
    id: "cooler_upright",
    labelVi: "Beverage Cooler",
    defaultWidth: 680,
    defaultDepth: 780,
    defaultHeight: 2000,
    defaultShelfCount: 5,
    temperatureZone: "chilled",
    sellable: true,
    promoCapable: false,
    color: "#0f1a2a",
    borderColor: "#22d3ee",
  },
  {
    id: "wall_shelf",
    labelVi: "Wall Shelf",
    defaultWidth: 900,
    defaultDepth: 410,
    defaultHeight: 1800,
    defaultShelfCount: 5,
    temperatureZone: "ambient",
    sellable: true,
    promoCapable: false,
    color: "#111111",
    borderColor: "#555555",
  },
  {
    id: "gondola_double",
    labelVi: "Gondola",
    defaultWidth: 900,
    defaultDepth: 760,
    defaultHeight: 1500,
    defaultShelfCount: 5,
    temperatureZone: "ambient",
    sellable: true,
    promoCapable: false,
    color: "#111111",
    borderColor: "#555555",
  },
  {
    id: "endcap",
    labelVi: "End Cap",
    defaultWidth: 900,
    defaultDepth: 350,
    defaultHeight: 1400,
    defaultShelfCount: 4,
    temperatureZone: "ambient",
    sellable: true,
    promoCapable: true,
    color: "#111111",
    borderColor: "#22c55e",
  },
  {
    id: "bakery_shelf",
    labelVi: "Bakery Shelf",
    defaultWidth: 1200,
    defaultDepth: 500,
    defaultHeight: 1600,
    defaultShelfCount: 4,
    temperatureZone: "ambient",
    sellable: true,
    promoCapable: true,
    color: "#3d2010",
    borderColor: "#d97706",
  },
  {
    id: "promo_island",
    labelVi: "Promo Island",
    defaultWidth: 1200,
    defaultDepth: 1200,
    defaultHeight: 900,
    defaultShelfCount: 2,
    temperatureZone: "ambient",
    sellable: true,
    promoCapable: true,
    color: "#7f1d1d",
    borderColor: "#ef4444",
  },
  {
    id: "checkout_impulse",
    labelVi: "Checkout Impulse",
    defaultWidth: 400,
    defaultDepth: 500,
    defaultHeight: 1200,
    defaultShelfCount: 4,
    temperatureZone: "ambient",
    sellable: true,
    promoCapable: true,
    color: "#111111",
    borderColor: "#555555",
  },
  {
    id: "entry_exit",
    labelVi: "Entry / Exit",
    defaultWidth: 1600,
    defaultDepth: 200,
    defaultHeight: 0,
    defaultShelfCount: 0,
    temperatureZone: "ambient",
    sellable: false,
    promoCapable: false,
    color: "#0a2a0a",
    borderColor: "#86efac",
  },
  {
    id: "annotation",
    labelVi: "Note / Annotation",
    defaultWidth: 500,
    defaultDepth: 500,
    defaultHeight: 0,
    defaultShelfCount: 0,
    temperatureZone: "ambient",
    sellable: false,
    promoCapable: false,
    color: "#78350f",
    borderColor: "#f59e0b",
  },
  {
    id: "obstacle",
    labelVi: "Column / Obstacle",
    defaultWidth: 400,
    defaultDepth: 400,
    defaultHeight: 3000,
    defaultShelfCount: 0,
    temperatureZone: "ambient",
    sellable: false,
    promoCapable: false,
    color: "#2a0a0a",
    borderColor: "#f87171",
  },
];

export const FIXTURE_MAP = new Map(FIXTURE_TYPES.map((f) => [f.id, f]));

const TEMP_BADGE: Record<string, string> = {
  chilled: "❄",
  frozen: "🧊",
  ambient: "",
};

export function getFixtureBadge(id: string): string {
  const def = FIXTURE_MAP.get(id as never);
  if (!def) return "";
  return TEMP_BADGE[def.temperatureZone] ?? "";
}
